name: CI Build Spring Boot App

on:
  push:
    branches: [ main ]     # Chạy khi có push lên nhánh main
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: self-hosted   # Sử dụng runner bạn đã cài trên Ubuntu

    steps:
      # 1️ Checkout source code từ GitHub
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2️ Cài Java (nếu runner không có sẵn)
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️ Build project bằng Maven
      - name: Build with Maven
        run: |
          cd /home/ubuntu/product_project/product_source
          mvn clean package -DskipTests

      # 4️ Kiểm tra artifact sau khi build
      - name: List built files
        run: ls -lh /home/ubuntu/product_project/product_source/target

      # 5️ Copy file .jar sang thư mục chạy app (CI phase)
      - name: Copy jar to deployment folder
        run: |
          mkdir -p /home/ubuntu/product_project/product_source/runapp/runapp
          cp /home/ubuntu/product_project/product_source/target/*.jar /home/ubuntu/product_project/product_source/runapp/product-management.jar
