name: CI Build Spring Boot App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Copy Jar
    runs-on: self-hosted
    # (Tuỳ chọn) có thể khai báo env ở cấp job nếu cần dùng trong nhiều step.
    env:
      SPRING_DATASOURCE_URL: "localhost:3306/productmanagement?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "productuser"
      SPRING_DATASOURCE_PASSWORD: "666888!2025"
      
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Show workspace
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls -la

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          
      # Cấp quyền thực thi cho file mvn
      - name: Ensure mvnw executable
        run: |
          cd ${{ github.workspace }}
          chmod +x mvnw
           
      # Build NGAY TRONG workspace của runner
      - name: Build with Maven
        working-directory: ${{ github.workspace }}
        run: ./mvnw -B clean package -DskipTests

      - name: List built artifacts
        run: ls -lh ${{ github.workspace }}/target

      # Copy .jar sang chỗ bạn muốn chạy app
      - name: Copy jar to run directory
        run: |
          cp ${{ github.workspace }}/target/*.jar \
             /home/ubuntu/product_project/product_source/product-management.jar
          chown ubuntu:ubuntu /home/ubuntu/product_project/product_source/product-management.jar

  deploy:
      env:
        APP_PORT: 8085
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ProductManagement?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: productuser
        SPRING_DATASOURCE_PASSWORD: 666888!2025
      runs-on: self-hosted
      needs: build

     steps:
        - name: Stop old process if running
          run: |
            echo "Stopping old process..."
            pgrep -f "product-management.jar" && pkill -f "product-management.jar" || echo "No process to stop"

        - name: Run Spring Boot app
          run: |
            echo "Starting Spring Boot app..."
            cd /home/ubuntu/product_project/product_source
            nohup java -jar \
              -Dserver.port=${APP_PORT} \
              -Dspring.datasource.url="${SPRING_DATASOURCE_URL}" \
              -Dspring.datasource.username="${SPRING_DATASOURCE_USERNAME}" \
              -Dspring.datasource.password="${SPRING_DATASOURCE_PASSWORD}" \
              product-management.jar > app.log 2>&1 &
            echo "App started on port ${APP_PORT}"
